insert into public.experience_points (
  destination_slug,
  theme_slug,
  slug,
  title,
  type,
  summary,
  good_for,
  not_best_for,
  booking_required,
  duration_minutes,
  typical_price_range,
  language_dependency,
  difficulty,
  foreign_visitor_friendliness,
  source_urls
)
values
  (
    'quanzhou',
    'qz-religious-diversity',
    'qz-religious-diversity-route',
    'Religious Diversity and Exchange Route',
    'walking_route',
    'A theme-led route linking Quanzhou''s multi-faith heritage to maritime exchange and port-city identity.',
    '{Middle East,Europe,United States,academic groups}',
    '{travelers wanting only visual check-in spots}',
    true,
    240,
    'medium',
    'high',
    'low',
    4,
    '{https://whc.unesco.org/en/list/1561/}'
  ),
  (
    'quanzhou',
    'qz-food-life',
    'qz-food-and-old-town-evening',
    'Food and Old-Town Evening',
    'food_route',
    'An evening route that uses food, street rhythm, and old-town atmosphere to make Quanzhou feel lived-in rather than museum-like.',
    '{Southeast Asia,Japan,Korea,North America,families}',
    '{travelers avoiding local food exploration}',
    false,
    180,
    'low-medium',
    'medium',
    'low',
    4,
    '{https://www.unesco.org/en/creative-cities/quanzhou}'
  ),
  (
    'quanzhou',
    'qz-craft-routes',
    'qz-dehua-porcelain-extension',
    'Dehua Porcelain Extension Day',
    'day_trip',
    'A design- and craft-focused extension that connects Quanzhou''s port history to Dehua''s Blanc de Chine legacy.',
    '{Europe,Japan,Korea,United States,design travelers}',
    '{travelers looking only for a short city walk}',
    true,
    480,
    'medium-high',
    'high',
    'medium',
    3,
    '{https://www.quanzhou.gov.cn/gastronomy/en/about/unesco-heritage/202412/t20241203_3112420.htm}'
  ),

  (
    'beijing',
    'bj-imperial-order',
    'bj-central-axis-reading',
    'Central Axis Reading Route',
    'walking_route',
    'A route that explains Beijing through ceremonial order, political space, and how the capital was composed as an idea.',
    '{first-time visitors,Europe,United States,academic groups}',
    '{travelers wanting only casual neighborhood wandering}',
    true,
    240,
    'medium',
    'high',
    'medium',
    4,
    '{https://whc.unesco.org/en/list/1714/}'
  ),
  (
    'beijing',
    'bj-literati-practice',
    'bj-calligraphy-and-courtyard-session',
    'Calligraphy and Courtyard Session',
    'craft_session',
    'A quieter Beijing experience centered on brush practice, cultural discipline, and the social texture of courtyard space.',
    '{Japan,academic groups,design travelers,slow travelers}',
    '{travelers who want only landmark coverage}',
    true,
    150,
    'medium',
    'high',
    'low',
    3,
    '{https://www.dolphinunion.com/post/beijing-hutong-experiences-for-foreign-tourists}'
  ),
  (
    'beijing',
    'bj-history-and-neighborhood',
    'bj-hutong-and-city-memory',
    'Hutong and City Memory Walk',
    'walking_route',
    'A neighborhood route focused on how daily life, old spatial logic, and memory survive inside the capital.',
    '{photography travelers,repeat visitors,North America,Europe}',
    '{travelers expecting only palace-scale history}',
    true,
    180,
    'medium',
    'medium',
    'low',
    4,
    '{https://english.visitbeijing.com.cn/article/47OMs0rcAFo}'
  ),

  (
    'jingdezhen',
    'jdz-imperial-kilns',
    'jdz-imperial-kiln-context',
    'Imperial Kiln Context Walk',
    'heritage_route',
    'A heritage-focused route that explains why Jingdezhen porcelain mattered to empire, trade, and global taste.',
    '{Europe,United States,academic groups,collectors}',
    '{travelers interested only in shopping}',
    true,
    180,
    'medium',
    'high',
    'low',
    4,
    '{https://whc.unesco.org/en/tentativelists/6265/}'
  ),
  (
    'jingdezhen',
    'jdz-material-culture',
    'jdz-collector-eye-session',
    'Collector''s Eye Session',
    'interpretive_session',
    'A focused session on glaze, form, object judgment, and how to look at ceramics with more precision.',
    '{collectors,design travelers,Japan,Europe,academic groups}',
    '{travelers wanting a casual sightseeing activity}',
    true,
    120,
    'medium-high',
    'high',
    'low',
    3,
    '{https://www.unesco.org/en/creative-cities/jingdezhen}'
  ),
  (
    'jingdezhen',
    'jdz-studio-making',
    'jdz-maker-neighborhood-halfday',
    'Maker Neighborhood Half-Day',
    'studio_route',
    'A half-day route through active maker areas, studio culture, and the everyday life of a still-working craft city.',
    '{makers,North America,Europe,photography travelers}',
    '{travelers uninterested in process}',
    true,
    240,
    'medium-high',
    'high',
    'medium',
    3,
    '{http://english.scio.gov.cn/internationalexchanges/2025-10/20/content_118132564.html}'
  ),

  (
    'chengdu',
    'cd-sichuan-flavor',
    'cd-market-and-flavor-morning',
    'Market and Flavor Morning',
    'food_route',
    'A route through morning market life, ingredient logic, and how Sichuan flavor is built before it reaches the table.',
    '{food travelers,Southeast Asia,Japan,Korea,United States}',
    '{travelers who dislike markets or local food environments}',
    false,
    180,
    'low-medium',
    'medium',
    'low',
    5,
    '{https://unesdoc.unesco.org/ark:/48223/pf0000192047}'
  ),
  (
    'chengdu',
    'cd-city-life',
    'cd-park-teahouse-neighborhood',
    'Park, Teahouse, and Neighborhood Route',
    'urban_route',
    'A slower city route built around park culture, teahouse atmosphere, and the social ease that defines Chengdu.',
    '{slow travelers,North America,Australia,repeat visitors}',
    '{travelers wanting only major attractions}',
    false,
    210,
    'low-medium',
    'medium',
    'low',
    5,
    '{https://www.dolphinunion.com/post/authentic-chengdu-teahouse-experience-for-foreign-travelers-can-truly-taste-the-city-slow-life}'
  ),
  (
    'chengdu',
    'cd-sichuan-flavor',
    'cd-evening-food-and-street-life',
    'Evening Food and Street Life',
    'food_route',
    'An evening route that uses appetite, movement, and local eating habits to explain the city''s social warmth.',
    '{food travelers,younger travelers,Southeast Asia,North America}',
    '{travelers wanting a quiet museum-led evening}',
    false,
    180,
    'medium',
    'medium',
    'low',
    4,
    '{https://www.unesco.org/en/creative-cities/chengdu}'
  ),

  (
    'chongqing',
    'cq-topography',
    'cq-multi-level-city-read',
    '8D Mountain City Read',
    'urban_route',
    'A route that decodes Chongqing as a surreal 8D mountain city shaped by slopes, bridges, stairs, rail, and river edges.',
    '{urbanists,photography travelers,United States,Europe}',
    '{travelers with low tolerance for walking or elevation changes}',
    true,
    210,
    'medium',
    'high',
    'high',
    3,
    '{https://www.cnn.com/travel/chongqing-china-tourism-cyberpunk-city-intl-hnk}'
  ),
  (
    'chongqing',
    'cq-food-and-wartime',
    'cq-hotpot-and-history-evening',
    'Hotpot and History Evening',
    'food_route',
    'A route connecting Chongqing''s bold appetite to labor, weather, urban density, and wartime memory.',
    '{food travelers,North America,Southeast Asia,urban culture travelers}',
    '{travelers avoiding spicy food or dense evening activity}',
    true,
    180,
    'medium',
    'medium',
    'low',
    4,
    '{http://www.chinadaily.com.cn/a/201710/23/WS5a0ced18a31061a738406ffb.html}'
  ),
  (
    'chongqing',
    'cq-night-city',
    'cq-river-night-views',
    'Cyberpunk Night Views and Urban Drama',
    'urban_route',
    'A visually led route that treats Chongqing''s neon skyline, river edges, and stacked movement as one cyberpunk urban system rather than isolated photo points.',
    '{Korea,Japan,photography travelers,younger travelers}',
    '{travelers preferring day-only itineraries}',
    true,
    150,
    'medium',
    'medium',
    'medium',
    4,
    '{https://www.chinadaily.com.cn/a/202104/14/WS60762274a31024ad0bab54d3.html}'
  ),

  (
    'jingmai_mountain',
    'jm-village-ritual',
    'jm-village-continuity-walk',
    'Village Continuity Walk',
    'village_route',
    'A village-based route focused on continuity, daily rhythm, and how tea culture lives through people rather than plantations alone.',
    '{slow travelers,North America,Australia,wellness travelers}',
    '{travelers seeking fast movement and dense checklists}',
    true,
    180,
    'medium',
    'medium',
    'medium',
    3,
    '{https://whc.unesco.org/en/list/1665/}'
  ),
  (
    'jingmai_mountain',
    'jm-slow-retreat',
    'jm-homestay-style-immersion',
    'Homestay-Style Immersion',
    'slow_stay',
    'A slower immersion format built around staying longer, moving lightly, and letting tea culture unfold through place and hospitality.',
    '{wellness travelers,Australia,tea travelers,premium slow travelers}',
    '{travelers needing luxury-city comfort expectations}',
    true,
    720,
    'medium-high',
    'high',
    'low',
    2,
    '{https://wildchina.com/2023/11/chinas-newest-unesco-site-jingmai-mountain/}'
  ),
  (
    'jingmai_mountain',
    'jm-ancient-tea-forest',
    'jm-tea-tasting-and-forest-context',
    'Tea Tasting and Forest Context',
    'tea_session',
    'A tasting-led session that connects flavor to ecology, understorey cultivation, and old tea-tree continuity.',
    '{tea travelers,Japan,Korea,Europe,design travelers}',
    '{travelers wanting only scenic photography}',
    true,
    120,
    'medium',
    'high',
    'low',
    3,
    '{https://whc.unesco.org/en/list/1665/}'
  ),

  (
    'wudang_mountain',
    'wd-taoist-mountain',
    'wd-sacred-architecture-route',
    'Sacred Architecture Route',
    'heritage_route',
    'A route through temple composition, mountain setting, and the architectural logic of a Taoist sacred landscape.',
    '{Europe,United States,academic groups,philosophy travelers}',
    '{travelers wanting only exercise or scenery}',
    true,
    240,
    'medium',
    'high',
    'medium',
    3,
    '{https://whc.unesco.org/en/list/705/}'
  ),
  (
    'wudang_mountain',
    'wd-reflective-china',
    'wd-quiet-mountain-morning',
    'Quiet Mountain Morning',
    'slow_route',
    'A slower early-day route oriented around mountain atmosphere, breath, and mental pace rather than attraction-counting.',
    '{slow travelers,premium travelers,Japan,Europe}',
    '{travelers seeking energetic all-day sightseeing}',
    false,
    150,
    'medium',
    'medium',
    'medium',
    3,
    '{https://www.fohb.gov.cn/info/2022-08/20220817112700_299.html}'
  ),
  (
    'wudang_mountain',
    'wd-internal-practice',
    'wd-beginner-internal-practice',
    'Beginner Internal Practice Session',
    'practice_session',
    'An entry-level session that translates internal practice into something meaningful for travelers without prior training.',
    '{wellness travelers,North America,Europe,entry-level cultural travelers}',
    '{travelers expecting performance-style martial arts entertainment}',
    true,
    90,
    'medium',
    'high',
    'medium',
    3,
    '{https://www.globaltimes.cn/page/202306/1291971.shtml}'
  )
on conflict (slug) do update set
  title = excluded.title,
  type = excluded.type,
  summary = excluded.summary,
  good_for = excluded.good_for,
  not_best_for = excluded.not_best_for,
  booking_required = excluded.booking_required,
  duration_minutes = excluded.duration_minutes,
  typical_price_range = excluded.typical_price_range,
  language_dependency = excluded.language_dependency,
  difficulty = excluded.difficulty,
  foreign_visitor_friendliness = excluded.foreign_visitor_friendliness,
  source_urls = excluded.source_urls,
  updated_at = timezone('utc', now());
